<?php

namespace Database\Seeders;

use App\Models\Stock;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class StockSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         $stocks = [
            // Banking Sector
            [
                'symbol' => 'GTB',
                'name' => 'Guaranty Trust Bank',
                'category' => 'banking',
                'current_price' => 42.50,
                'opening_price' => 41.80,
                'day_high' => 43.20,
                'day_low' => 41.50,
                'week_high' => 45.00,
                'week_low' => 40.00,
                'market_cap' => 1250000000000.00,
                'volume' => 5400000,
                'price_change' => 0.70,
                'price_change_percentage' => 1.67,
                'description' => 'One of Nigeria\'s leading financial institutions, offering comprehensive banking services.',
                'is_active' => true,
            ],
            [
                'symbol' => 'ZENITH',
                'name' => 'Zenith Bank Plc',
                'category' => 'banking',
                'current_price' => 38.25,
                'opening_price' => 38.50,
                'day_high' => 39.00,
                'day_low' => 37.80,
                'week_high' => 40.50,
                'week_low' => 36.00,
                'market_cap' => 1150000000000.00,
                'volume' => 4800000,
                'price_change' => -0.25,
                'price_change_percentage' => -0.65,
                'description' => 'A leading Nigerian bank providing retail and corporate banking services.',
                'is_active' => true,
            ],
            [
                'symbol' => 'ACCESS',
                'name' => 'Access Bank Plc',
                'category' => 'banking',
                'current_price' => 15.80,
                'opening_price' => 15.50,
                'day_high' => 16.00,
                'day_low' => 15.40,
                'week_high' => 17.20,
                'week_low' => 14.80,
                'market_cap' => 565000000000.00,
                'volume' => 8200000,
                'price_change' => 0.30,
                'price_change_percentage' => 1.94,
                'description' => 'Nigeria\'s largest bank by assets, serving individuals and businesses.',
                'is_active' => true,
            ],
            [
                'symbol' => 'UBA',
                'name' => 'United Bank for Africa',
                'category' => 'banking',
                'current_price' => 22.40,
                'opening_price' => 22.10,
                'day_high' => 22.80,
                'day_low' => 21.90,
                'week_high' => 24.00,
                'week_low' => 21.00,
                'market_cap' => 760000000000.00,
                'volume' => 6100000,
                'price_change' => 0.30,
                'price_change_percentage' => 1.36,
                'description' => 'Pan-African financial services group operating in 20 African countries.',
                'is_active' => true,
            ],

            // Oil & Gas Sector
            [
                'symbol' => 'SEPLAT',
                'name' => 'Seplat Energy Plc',
                'category' => 'oil_gas',
                'current_price' => 3250.00,
                'opening_price' => 3180.00,
                'day_high' => 3280.00,
                'day_low' => 3150.00,
                'week_high' => 3400.00,
                'week_low' => 3000.00,
                'market_cap' => 1920000000000.00,
                'volume' => 125000,
                'price_change' => 70.00,
                'price_change_percentage' => 2.20,
                'description' => 'Leading Nigerian independent oil and gas company.',
                'is_active' => true,
            ],
            [
                'symbol' => 'TOTAL',
                'name' => 'TotalEnergies Marketing Nigeria',
                'category' => 'oil_gas',
                'current_price' => 485.50,
                'opening_price' => 490.00,
                'day_high' => 495.00,
                'day_low' => 482.00,
                'week_high' => 510.00,
                'week_low' => 475.00,
                'market_cap' => 490000000000.00,
                'volume' => 85000,
                'price_change' => -4.50,
                'price_change_percentage' => -0.92,
                'description' => 'Leading petroleum products marketing company in Nigeria.',
                'is_active' => true,
            ],
            [
                'symbol' => 'OANDO',
                'name' => 'Oando Plc',
                'category' => 'oil_gas',
                'current_price' => 58.20,
                'opening_price' => 56.80,
                'day_high' => 59.00,
                'day_low' => 56.50,
                'week_high' => 62.00,
                'week_low' => 54.00,
                'market_cap' => 680000000000.00,
                'volume' => 3400000,
                'price_change' => 1.40,
                'price_change_percentage' => 2.46,
                'description' => 'Indigenous energy group engaged in exploration and distribution.',
                'is_active' => true,
            ],

            // Technology Sector
            [
                'symbol' => 'MTNN',
                'name' => 'MTN Nigeria',
                'category' => 'telecommunications',
                'current_price' => 285.00,
                'opening_price' => 282.50,
                'day_high' => 288.00,
                'day_low' => 281.00,
                'week_high' => 295.00,
                'week_low' => 275.00,
                'market_cap' => 5830000000000.00,
                'volume' => 890000,
                'price_change' => 2.50,
                'price_change_percentage' => 0.89,
                'description' => 'Nigeria\'s largest telecommunications network provider.',
                'is_active' => true,
            ],
            [
                'symbol' => 'AIRTELAFRI',
                'name' => 'Airtel Africa Plc',
                'category' => 'telecommunications',
                'current_price' => 1850.00,
                'opening_price' => 1820.00,
                'day_high' => 1870.00,
                'day_low' => 1810.00,
                'week_high' => 1950.00,
                'week_low' => 1780.00,
                'market_cap' => 6920000000000.00,
                'volume' => 245000,
                'price_change' => 30.00,
                'price_change_percentage' => 1.65,
                'description' => 'Pan-African telecommunications company with operations in 14 countries.',
                'is_active' => true,
            ],

            // Consumer Goods
            [
                'symbol' => 'DANGCEM',
                'name' => 'Dangote Cement Plc',
                'category' => 'manufacturing',
                'current_price' => 465.00,
                'opening_price' => 460.00,
                'day_high' => 470.00,
                'day_low' => 458.00,
                'week_high' => 485.00,
                'week_low' => 450.00,
                'market_cap' => 7900000000000.00,
                'volume' => 1250000,
                'price_change' => 5.00,
                'price_change_percentage' => 1.09,
                'description' => 'Africa\'s leading cement manufacturer with presence across the continent.',
                'is_active' => true,
            ],
            [
                'symbol' => 'NESTLE',
                'name' => 'Nestle Nigeria Plc',
                'category' => 'consumer_goods',
                'current_price' => 1420.00,
                'opening_price' => 1405.00,
                'day_high' => 1435.00,
                'day_low' => 1400.00,
                'week_high' => 1480.00,
                'week_low' => 1380.00,
                'market_cap' => 1150000000000.00,
                'volume' => 78000,
                'price_change' => 15.00,
                'price_change_percentage' => 1.07,
                'description' => 'Leading nutrition, health and wellness company.',
                'is_active' => true,
            ],
            [
                'symbol' => 'FLOUR',
                'name' => 'Flour Mills of Nigeria',
                'category' => 'consumer_goods',
                'current_price' => 38.50,
                'opening_price' => 37.80,
                'day_high' => 39.00,
                'day_low' => 37.50,
                'week_high' => 41.00,
                'week_low' => 36.00,
                'market_cap' => 385000000000.00,
                'volume' => 2100000,
                'price_change' => 0.70,
                'price_change_percentage' => 1.85,
                'description' => 'Nigeria\'s leading food and agro-allied group.',
                'is_active' => true,
            ],
            [
                'symbol' => 'GUINNESS',
                'name' => 'Guinness Nigeria Plc',
                'category' => 'consumer_goods',
                'current_price' => 58.00,
                'opening_price' => 57.20,
                'day_high' => 58.80,
                'day_low' => 56.80,
                'week_high' => 62.00,
                'week_low' => 55.00,
                'market_cap' => 148000000000.00,
                'volume' => 1850000,
                'price_change' => 0.80,
                'price_change_percentage' => 1.40,
                'description' => 'Leading beverage company producing iconic beer and spirits brands.',
                'is_active' => true,
            ],

            // Manufacturing
            [
                'symbol' => 'BUACEMENT',
                'name' => 'BUA Cement Plc',
                'category' => 'manufacturing',
                'current_price' => 95.50,
                'opening_price' => 94.20,
                'day_high' => 96.80,
                'day_low' => 93.80,
                'week_high' => 100.00,
                'week_low' => 90.00,
                'market_cap' => 3050000000000.00,
                'volume' => 4200000,
                'price_change' => 1.30,
                'price_change_percentage' => 1.38,
                'description' => 'Fast-growing cement manufacturing company in Nigeria.',
                'is_active' => true,
            ],
            [
                'symbol' => 'WAPCO',
                'name' => 'Lafarge Africa Plc',
                'category' => 'manufacturing',
                'current_price' => 28.75,
                'opening_price' => 28.30,
                'day_high' => 29.20,
                'day_low' => 28.10,
                'week_high' => 30.50,
                'week_low' => 27.00,
                'market_cap' => 345000000000.00,
                'volume' => 5600000,
                'price_change' => 0.45,
                'price_change_percentage' => 1.59,
                'description' => 'Leading building materials company producing cement and aggregates.',
                'is_active' => true,
            ],
        ];

        foreach ($stocks as $stock) {
            Stock::create($stock);
        }

        $this->command->info('Stocks seeded successfully!');
    
    }
}
